"use strict";
const SIZE=20;let board=[];
const state={screen:"battle",round:1,units:[],selected:null,turnOrder:[],turnIndex:0,mode:null,highlight:[],log:[],victory:false,defeat:false,core:null,tool:"floor",editorSelected:null};
const templates={
 powerkim:{id:"powerkim",name:"Powerkim",short:"P",team:"hero",className:"Nahkampf / Tank",x:2,y:17,hp:180,maxHp:180,attack:20,defense:18,stability:25,movement:5,range:1,damage:35,knockback:3,abilityName:"Kraftschlag",abilityCost:1,color:"#55baff"},
 visor:{id:"visor",name:"Visor",short:"V",team:"hero",className:"Fernkampf / Taktiker",x:3,y:17,hp:80,maxHp:80,attack:22,defense:10,stability:15,movement:6,range:10,damage:24,knockback:1,abilityName:"Präzisionsschuss",abilityCost:1,color:"#8be5ff"},
 watson:{id:"watson",name:"Watson",short:"W",team:"hero",className:"Heiler / Fliegend",x:4,y:17,hp:100,maxHp:100,attack:8,defense:10,stability:20,movement:8,range:8,heal:40,abilityName:"Heilstrahl",abilityCost:1,flying:true,color:"#92f6a7"},
 nyra:{id:"nyra",name:"Nyra",short:"N",team:"hero",className:"Spionin / Fallen",x:1,y:18,hp:70,maxHp:70,attack:15,defense:12,stability:15,movement:9,range:1,damage:18,knockback:2,abilityName:"Falle legen",abilityCost:1,color:"#d8b1ff"},
 drone1:{id:"drone1",name:"Sicherheitsdrohne 1",short:"D",team:"enemy",className:"Fernkampf / Fliegend",x:16,y:3,hp:40,maxHp:40,attack:14,defense:3,stability:10,movement:8,range:7,damage:14,knockback:1,abilityName:"Laserschuss",color:"#ff9292",flying:true},
 drone2:{id:"drone2",name:"Sicherheitsdrohne 2",short:"D",team:"enemy",className:"Fernkampf / Fliegend",x:17,y:5,hp:40,maxHp:40,attack:14,defense:3,stability:10,movement:8,range:7,damage:14,knockback:1,abilityName:"Laserschuss",color:"#ff9292",flying:true},
 bulwark:{id:"bulwark",name:"Bulwark",short:"B",team:"enemy",className:"Schwerer Tank",x:15,y:15,hp:220,maxHp:220,attack:26,defense:20,stability:40,movement:3,range:1,damage:16,knockback:3,abilityName:"Rückstoßangriff",color:"#ffb86c"}
};
const STATUS={burning:{label:"Brennend",duration:2},stunned:{label:"Betäubt",duration:1},paralyzed:{label:"Paralysiert",duration:1},knocked_down:{label:"Am Boden",duration:1},slowed:{label:"Verlangsamt",duration:1},shielded:{label:"Geschützt",duration:1},marked:{label:"Markiert",duration:1}};
function render(){const t=document.getElementById("screen-title"),s=document.getElementById("screen-status"),u=currentUnit();if(t)t.textContent=state.screen==="battle"?"Arena Heroes":"Arena Editor";if(s)s.textContent=state.screen!=="battle"?"Karte bearbeiten":state.victory?"Sieg":state.defeat?"Niederlage":u?`Runde ${state.round} · ${u.name} ist an der Reihe`:`Runde ${state.round}`;state.screen==="battle"?battle():editor()}
function makeUnit(t){return {...t,id:`${t.id}-${Math.random().toString(36).slice(2,8)}`,alive:true,ap:2,acted:false,moveLeft:t.movement,statuses:[],x:t.x,y:t.y}}
function cell(x,y){return x>=0&&y>=0&&x<SIZE&&y<SIZE?board[y][x]:null}function at(x,y){return state.units.find(u=>u.alive&&u.x===x&&u.y===y)}function atAny(x,y){return state.units.find(u=>u.x===x&&u.y===y)}function currentUnit(){return state.turnOrder[state.turnIndex]||null}function dist(a,b){return Math.max(Math.abs(a.x-b.x),Math.abs(a.y-b.y))}function log(v){state.log.unshift(v);state.log=state.log.slice(0,18)}
function hasStatus(u,id){return u?.statuses.some(s=>s.id===id)}function addStatus(u,id,duration=STATUS[id]?.duration||1){if(!u||!STATUS[id])return;const old=u.statuses.find(s=>s.id===id);if(old)old.remaining=Math.max(old.remaining,duration);else u.statuses.push({id,remaining:duration});log(`${u.name}: ${STATUS[id].label}.`)}function removeStatus(u,id){if(u)u.statuses=u.statuses.filter(s=>s.id!==id)}function statusText(u){return u.statuses.length?u.statuses.map(s=>STATUS[s.id]?.label||s.id).join(", "):"Normal"}
function setupMap(){board=Array.from({length:SIZE},()=>Array.from({length:SIZE},()=>({type:"floor",walk:true,los:false,cover:0})));const set=(x,y,type)=>{const c=cell(x,y);if(!c)return;c.type=type;c.walk=!['wall','container','vehicle'].includes(type);c.los=['wall','container'].includes(type);c.cover=type==="tree"?1:type==="wall"||type==="container"?2:0};for(let i=0;i<SIZE;i++){set(i,0,"wall");set(i,19,"wall");set(0,i,"wall");set(19,i,"wall")}[[4,4],[5,4],[6,4],[4,5],[6,5],[4,6],[5,6],[6,6],[10,10],[11,10],[12,10],[11,11],[12,11],[13,11],[10,12],[11,12],[12,12]].forEach(p=>set(p[0],p[1],"wall"));[[3,2],[12,2],[3,3],[12,3],[8,8],[9,8],[10,8],[16,12],[16,13]].forEach(p=>set(p[0],p[1],"container"));[[6,13],[15,9]].forEach(p=>set(p[0],p[1],"vehicle"));for(let x=8;x<=12;x++){set(x,15,"water");set(x,16,"water")}set(13,13,"core");state.core={name:"Nexus-Energiekern",x:13,y:13,hp:150,maxHp:150,defense:10,alive:true}}
function startRound(){state.turnOrder=state.units.filter(u=>u.alive).sort((a,b)=>b.movement-a.movement||Math.random()-.5);state.turnIndex=0;state.turnOrder.forEach(u=>{u.ap=2;u.acted=false;u.moveLeft=u.movement});skipUnavailable();log(`Runde ${state.round}: ${state.turnOrder.map(u=>`${u.name} (${u.movement})`).join(" → ")}`)}
function skipUnavailable(){let n=0;while(n++<state.turnOrder.length){const u=currentUnit();if(!u||!u.alive){advanceTurn(true);continue}if(hasStatus(u,"paralyzed")||hasStatus(u,"stunned")){log(`${u.name} kann nicht handeln (${statusText(u)}).`);advanceTurn(true);continue}return}}
function advanceTurn(skipped=false){if(!state.turnOrder.length)return;const u=currentUnit();if(u&&!skipped)u.acted=true;state.turnIndex++;if(state.turnIndex>=state.turnOrder.length){state.round++;startRound()}else skipUnavailable()}
function enter(u,x,y){const c=cell(x,y);return c&&c.walk&&(c.type!=="water"||u.flying)&&!at(x,y)}function reachable(u){const a=[];for(let y=0;y<SIZE;y++)for(let x=0;x<SIZE;x++){const d=Math.abs(u.x-x)+Math.abs(u.y-y);if(d>0&&d<=u.moveLeft&&enter(u,x,y))a.push({x,y})}return a}
function los(a,b){const n=Math.max(Math.abs(a.x-b.x),Math.abs(a.y-b.y));for(let i=1;i<n;i++){const c=cell(a.x+Math.round((b.x-a.x)*i/n),a.y+Math.round((b.y-a.y)*i/n));if(c?.los)return false}return true}function cover(t){const c=cell(t.x,t.y);return c?.cover===2?8:c?.cover===1?4:0}function hit(a,t){return a.attack+Math.floor(Math.random()*6)-(t.defense||0)-cover(t)+(hasStatus(t,"marked")?-3:0)}
function damage(a,t,n){if(!t?.alive)return;const d=Math.max(1,n-(hasStatus(t,"shielded")?Math.ceil((t.defense||0)*.5):t.defense||0));t.hp=Math.max(0,t.hp-d);log(`${a.name} verursacht ${d} Schaden an ${t.name}.`);if(!t.hp){t.alive=false;t.ap=0;log(`${t.name} ist kampfunfähig.`)}}
function knockback(t,a,f){const dx=Math.sign(t.x-a.x),dy=Math.sign(t.y-a.y);for(let i=0;i<f&&t.alive;i++){const x=t.x+dx,y=t.y+dy,c=cell(x,y),block=at(x,y);if(!c||!c.walk){damage({name:"Kollision"},t,8);break}if(block){damage({name:"Kollision"},t,6);damage({name:"Kollision"},block,6);break}t.x=x;t.y=y}}
function doAttack(t,ability=false){const a=currentUnit();if(!a||a.ap<1||!t||t.team===a.team||dist(a,t)>a.range||!los(a,t)||hasStatus(a,"knocked_down"))return;if(hit(a,t)<=0){log(`${a.name} verfehlt ${t.name}.`);spend(a);finishAction();return}damage(a,t,ability?a.damage||10:a.attack+5);if(t.alive&&a.knockback)knockback(t,a,a.knockback);if(t.alive&&a.knockback>=(t.stability||20))addStatus(t,"knocked_down");spend(a);finishAction()}
function spend(u){u.ap=Math.max(0,u.ap-1);u.acted=true}function finishAction(){state.mode=null;state.highlight=[];check();render()}function useAbility(t){const a=currentUnit();if(!a||a.ap<1)return;if(a.heal){if(!t||t.team!==a.team||!los(a,t))return;t.hp=Math.min(t.maxHp,t.hp+a.heal);log(`${a.name} heilt ${t.name} um ${a.heal}.`);spend(a);finishAction()}else doAttack(t,true)}function move(x,y){const u=currentUnit();if(!u||u.ap<1||hasStatus(u,"knocked_down")||!state.highlight.some(p=>p.x===x&&p.y===y))return;const d=Math.abs(u.x-x)+Math.abs(u.y-y);u.x=x;u.y=y;u.moveLeft-=d;spend(u);state.highlight=reachable(u);render()}
function endTurn(){const u=currentUnit();if(!u)return;if(hasStatus(u,"knocked_down")&&u.ap){removeStatus(u,"knocked_down");spend(u);log(`${u.name} steht auf.`)}else{log(`${u.name} beendet seinen Zug.`);state.mode=null;state.highlight=[];advanceTurn()}check();render()}function check(){if(!state.units.some(u=>u.alive&&u.team==="hero"))state.defeat=true;if(state.core&&!state.core.alive)state.victory=true}
function clickTile(x,y){const u=currentUnit(),t=at(x,y);if(!u)return;if(state.mode==="move")return move(x,y);if(state.mode==="attack")return t?doAttack(t):undefined;if(state.mode==="ability")return t?useAbility(t):undefined;if(t?.team==="hero")state.selected=t.id;render()}
function mode(m){const u=currentUnit();if(!u||u.ap<1||hasStatus(u,"paralyzed")||hasStatus(u,"stunned"))return;state.mode=m;state.highlight=m==="move"?reachable(u):state.units.filter(t=>t.alive&&(m==="ability"&&u.heal?t.team===u.team&&t.hp<t.maxHp:t.team!==u.team)&&dist(u,t)<=u.range&&los(u,t)).map(t=>({x:t.x,y:t.y}));render()}
function boardView(){const r=document.getElementById("board");if(!r)return;r.innerHTML="";for(let y=0;y<SIZE;y++)for(let x=0;x<SIZE;x++){const e=document.createElement("div"),c=cell(x,y);e.className=`tile ${c.type}`;if(state.highlight.some(p=>p.x===x&&p.y===y))e.classList.add("highlight");const u=atAny(x,y);if(u){const q=document.createElement("div");q.className=`unit ${u.team} ${u===currentUnit()?"selected":""} ${u.alive?"":"defeated"}`;q.style.background=`linear-gradient(${u.color},#1d4f80)`;q.innerHTML=`<span class="letter">${u.short}</span><div class="hpbar"><span style="width:${Math.max(0,u.hp/u.maxHp*100)}%"></span></div><div class="hptext">${u.alive?`${u.hp}/${u.maxHp}`:"DOWN"}</div>`;if(!u.alive){const d=document.createElement("div");d.className="defeated-label";d.textContent="KAMPFUNFÄHIG";q.appendChild(d)}else if(u.statuses.length){const m=document.createElement("div");m.className="marker";m.textContent=u.statuses[0].id[0].toUpperCase();q.appendChild(m)}e.appendChild(q)}if(state.core?.alive&&state.core.x===x&&state.core.y===y){const l=document.createElement("div");l.className="label";l.textContent="E";e.appendChild(l)}e.onclick=()=>state.screen==="battle"?clickTile(x,y):editorClick(x,y);r.appendChild(e)}}
function battle(){const u=currentUnit();document.getElementById("workspace").innerHTML=`<div id="board-container"><div id="board"></div></div><aside id="sidebar"><div class="panel"><h3>Aktiver Zug</h3><div id="unit-info"></div><div class="grid"><button data-a="move">Bewegen [M]</button><button data-a="attack">Angriff [A]</button><button class="primary" data-a="ability">Spezial [S]</button><button class="warning wide" data-a="end">Zug beenden [Enter]</button></div></div><div class="panel"><h3>Initiative</h3><div id="initiative"></div></div><div class="panel"><h3>Protokoll</h3><div id="log"></div></div></aside>`;boardView();document.getElementById("unit-info").innerHTML=u?`<div class="card active"><span><b>${u.name}</b><small class="type">${u.className}</small></span><b>${u.hp}/${u.maxHp}</b></div><div class="stats"><span>AP</span><b>${u.ap}</b></div><div class="stats"><span>Angriffsreichweite</span><b>${u.range} Felder</b></div><div class="stats ability-info"><span>Spezialangriff</span><b>${u.abilityName||"Keine"}</b><small>${u.heal?`Heilt ${u.heal} HP`: `Schaden ${u.damage||u.attack} · Kosten ${u.abilityCost||1} AP`}</small></div><div class="stats"><span>Status</span><b>${statusText(u)}</b></div>`:"Kein aktiver Zug";document.getElementById("initiative").innerHTML=state.turnOrder.map((x,i)=>`<div class="card ${i===state.turnIndex?"active":""} ${x.alive?"":"defeated"}"><span>${x.name}<small class="type">${statusText(x)}</small></span><b>${x.alive?`${x.hp}/${x.maxHp}`:"DOWN"}</b></div>`).join("");document.getElementById("log").innerHTML=state.log.map(x=>`<div>${x}</div>`).join("");document.querySelectorAll("[data-a]").forEach(b=>b.onclick=()=>b.dataset.a==="move"?mode("move"):b.dataset.a==="attack"?mode("attack"):b.dataset.a==="ability"?mode("ability"):endTurn())}
function editor(){document.getElementById("workspace").innerHTML=`<div id="board-container"><div id="board"></div></div><aside id="sidebar"><div class="panel"><h3>Editor-Werkzeuge</h3><div class="editor-tools">${["floor","wall","container","vehicle","water","tree","core","delete"].map(x=>`<button data-tool="${x}">${x==="delete"?"Löschen":x}</button>`).join("")}</div></div><div class="panel"><h3>Einheiten platzieren</h3><div class="editor-tools">${Object.values(templates).map(t=>`<button data-unit="${t.id}">${t.name}</button>`).join("")}</div><button id="clear-map" class="warning">Karte leeren</button><button id="save-map" class="success">Karte speichern</button><button id="load-map">Karte laden</button><button id="test-map" class="primary">Karte testen</button></div></aside>`;boardView();document.querySelectorAll("[data-tool]").forEach(b=>b.onclick=()=>{state.tool=b.dataset.tool;state.editorSelected=null;render()});document.querySelectorAll("[data-unit]").forEach(b=>b.onclick=()=>{state.editorSelected=b.dataset.unit;state.tool="unit";render()});document.getElementById("clear-map").onclick=()=>{setupMap();state.units=[];render()};document.getElementById("save-map").onclick=()=>{localStorage.setItem("arena-heroes-map",JSON.stringify({board,units:state.units,core:state.core}));log("Karte gespeichert.")};document.getElementById("load-map").onclick=()=>{const raw=localStorage.getItem("arena-heroes-map");if(!raw)return;const data=JSON.parse(raw);board=data.board;state.units=data.units;state.core=data.core;state.screen="editor";render()};document.getElementById("test-map").onclick=()=>{state.screen="battle";state.round=1;startRound();render()}}
function editorClick(x,y){if(state.tool==="unit"){const t=templates[state.editorSelected];if(!t||atAny(x,y))return;state.units.push(makeUnit({...t,x,y}));render();return}const c=cell(x,y);if(!c)return;if(state.tool==="delete"){c.type="floor";c.walk=true;c.los=false;c.cover=0}else{c.type=state.tool;c.walk=!['wall','container','vehicle'].includes(state.tool);c.los=['wall','container'].includes(state.tool);c.cover=state.tool==="tree"?1:state.tool==="wall"||state.tool==="container"?2:0;if(state.tool==="core")state.core={name:"Nexus-Energiekern",x,y,hp:150,maxHp:150,defense:10,alive:true}}render()}
document.getElementById("battle-button").onclick=()=>{state.screen="battle";render()};document.getElementById("editor-button").onclick=()=>{state.screen="editor";render()};document.getElementById("abort-button").onclick=()=>{state.screen="editor";render()};document.addEventListener("keydown",e=>{if(state.screen!=="battle")return;const k=e.key.toLowerCase();if(k==="m")mode("move");else if(k==="a")mode("attack");else if(k==="s")mode("ability");else if(e.key==="Enter")endTurn();else if(e.key==="Escape"){state.mode=null;state.highlight=[];render()}});
setupMap();state.units=Object.values(templates).map(makeUnit);state.selected=state.units[0].id;startRound();render();
